server:
  port: 3002
spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 10.18.111.17:8848
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.18.111.28:1521:PROD1
    username: xyjc
    password: xyjc
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: xyjc
      jdbc-url: jdbc:oracle:thin:@10.18.111.28:1521:PROD1
      password: xyjc

feign:
  hystrix:
    enabled: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #ID全局策略配置
  global-config:
    db-config:
      id-type: uuid
  type-aliases-package: cn.com.chenxin.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    io:
      seata: info
seata:
  tx-service-group: chenxin_tx_group
  config:
    type: file
    file:
      name: file.conf
  service:
    grouplist:
      default: 10.18.111.17:8091
  registry:
    type: nacos
    nacos:
      server-addr: 10.18.111.17:8848
      cluster: default
      group: SEATA_GROUP
  client:
    undo:
      log-serialization: kryo